### ISSUE TITLE
Scrape Yale Face Book

### ISSUE THREAD

**Issue by ericyoondotcom** [Yalies/Yalies#5]
Modify `facebook.ts` to scrape the Yale Face Book.

Find a good HTML parsing library... some good ones [here](https://www.scrapingdog.com/blog/html-parsing-libraries-javascript/)?

Refer to v1 code in `face_book.py`.

Make sure to use JS `async`/`await` syntax.

**Comment by bexoo** [comment]
Has some issues with scraping address as 'address \n major'
